apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application-deployment
spec:
  selector:
    matchLabels:
      app: my-application
  template:
    metadata:
      labels:
        app: my-application
    spec:
      containers:
      - name: my-application
        image: iersinyavas/my-application:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: my-application-service
spec:
  selector:
    app: my-application
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 31111
      name: http
  externalIPs:
    - 192.168.49.2


